# Generated by Django 4.1.5 on 2023-02-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='detalle',
            field=models.CharField(default=True, max_length=500),
        ),
    ]
