# Generated by Django 4.1.5 on 2023-02-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clients_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='detalle',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
