# Generated by Django 4.1.5 on 2023-02-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_clients_detalle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='phone',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='type',
            new_name='tipo',
        ),
    ]
