# Generated by Django 4.1.5 on 2023-02-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
