# Generated by Django 4.1.5 on 2023-02-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='picture',
        ),
    ]
