# Generated by Django 4.1.5 on 2023-02-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_products_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='detalle',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
