# Generated by Django 4.1.5 on 2023-02-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='detalle',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
