# Generated by Django 4.1.5 on 2023-02-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='detalle',
            field=models.CharField(max_length=500),
        ),
    ]
