# Generated by Django 4.1.5 on 2023-02-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_products_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
