# Generated by Django 4.1.5 on 2023-02-06 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_products_product_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_picture',
        ),
    ]
